name: Validate Data
on:
  - push
jobs:
  validate-data:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Validate workflows
        run: |
          cat frontend-deployment.yaml
          cat frontend-service.yaml
        working-directory: ./simple

      - name: Check the K8s Object
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated Change
          branch: stable
