name: Validate container image 
on:
  - push

jobs:
  validate-data-Docker:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    container:
      image: gcr.io/google-samples/gb-frontend:v4
    steps:
      - name: Validate workflows
        run: |
          cat controllers.js
          cat index.html
          php guestbook.php
        working-directory: /var/www/html

      - name: Check the Container image
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated Change
          branch: stable
