name: Validate data inside a Docker container 
on: push

jobs:
  validate-data-Docker:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    container:
      image: docker.io/ubuntu:20.04
    steps:
      - uses: actions/checkout@v2

      - name: Validate workflows
        run: |
          cat frontend-deployment.yaml
          cat frontend-service.yaml
          cat failure
        working-directory: ./simple
